
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:50101/eureka/ #, http://${eureka.instance.hostname}:50102/eureka/  ,http://${eureka.instance.hostname}:50103/eureka/
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）

---
server:
  port: 50101

spring:
  profiles: peer1
  application:
    name: xc-govern-center-${spring.profiles} #指定服务名
eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:50102/eureka/ #,http://${eureka.instance.hostname}:50103/eureka/

---

server:
  port: 50102

spring:
  profiles: peer2
  application:
    name: xc-govern-center-${spring.profiles} #指定服务名

eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:50101/eureka/ #,http://${eureka.instance.hostname}:50103/eureka/

---

server:
  port: 50103

spring:
  profiles: peer3
  application:
    name: xc-govern-center-${spring.profiles} #指定服务名

eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:50101/eureka/,http://${eureka.instance.hostname}:50102/eureka/
