server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:root@localhost:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: server
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  upload-location: D:/XueCheng/video/
  mq:
    routingkey-media-video: routingkey_media_video
    queue-media-video-processor: queue_media_video_processor

  video-location: D:/XueCheng/video/
  ffmpeg-path: D:/XueCheng/ffmpeg/bin/ffmpeg.exe